version: '3'
services:

  yum:
    container_name: senzing-yum
    environment:
      SENZING_ACCEPT_EULA: "${SENZING_ACCEPT_EULA:-no}"
    image: senzing/yum:${SENZING_YUM_VERSION:-1.0.0}
    networks:
      - backend
    restart: on-failure
    volumes:
      - ${SENZING_DATA_DIR:-/opt/senzing/data}:/opt/senzing/data
      - ${SENZING_ETC_DIR:-/etc/opt/senzing}:/etc/opt/senzing
      - ${SENZING_G2_DIR:-/opt/senzing/g2}:/opt/senzing/g2
      - ${SENZING_VAR_DIR:-/var/opt/senzing}:/var/opt/senzing

networks:
  backend:
