version: '3'
services:

  g2configinit:
    image: senzing/g2-configuration-initializer:latest
    container_name: senzing-g2-configuration-initializer
    environment:
      SENZING_SUBCOMMAND: initialize
    networks:
      - backend
    restart: on-failure
    volumes:
      - ${SENZING_DIR:-/opt/senzing}:/opt/senzing

  sqliteweb:
    image: coleifer/sqlite-web
    container_name: senzing-sqlite-web
    environment:
      SQLITE_DATABASE: G2C.db
    networks:
      - backend
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ${SENZING_DIR:-/opt/senzing}/g2/sqldb:/data

networks:
  backend:
