version: '3'
services:

  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: senzing-rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
    networks:
      - backend
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ${RABBITMQ_STORAGE:-/storage/docker/senzing/docker-compose-rabbitmq-postgres/rabbitmq}:/bitnami

  mockdata:
    image: senzing/mock-data-generator
    container_name: senzing-mock-data-generator
    depends_on:
      - rabbitmq
    environment:
#     See https://github.com/Senzing/docker-mock-data-generator#configuration
      SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
      SENZING_RABBITMQ_HOST: senzing-rabbitmq
      SENZING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
      SENZING_RABBITMQ_QUEUE: senzing-rabbitmq-queue
      SENZING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
      SENZING_RECORD_MAX: 10000
      SENZING_RECORD_MONITOR: 1000
      SENZING_SUBCOMMAND: url-to-rabbitmq
    networks:
      - backend
    restart: on-failure

  db2:
    image: senzing/db2express-c:latest
    command: db2start
    container_name: senzing-db2
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: ${DB2INST1_PASSWORD:-db2inst1}
    networks:
      - backend
    ports:
      - 50000:50000
    volumes:
      - ${DB2_STORAGE:-/storage/docker/senzing/docker-compose-db2-demo}:/home/db2inst1/db2inst1
      - ${SENZING_DIR:-/opt/senzing}:/opt/senzing

  loader:
    image: senzing/stream-loader
    container_name: senzing-stream-loader
    depends_on:
      - rabbitmq
    environment:
      LC_CTYPE: en_US.utf8
#     See https://github.com/Senzing/stream-loader#configuration
      SENZING_DATA_SOURCE: ${SENZING_DATA_SOURCE:-TEST}
      SENZING_DATABASE_URL: "db2://${DB2_USERNAME:-db2inst1}:${DB2_PASSWORD:-db2inst1}@senzing-db2:50000/${DB2_DB:-G2}"
      SENZING_ENTITY_TYPE: ${SENZING_ENTITY_TYPE:-TEST}
      SENZING_MONITORING_PERIOD: ${SENZING_MONITORING_PERIOD:-300}
      SENZING_PROCESSES: ${SENZING_PROCESSES:-1}
      SENZING_RABBITMQ_HOST: senzing-rabbitmq
      SENZING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
      SENZING_RABBITMQ_QUEUE: senzing-rabbitmq-queue
      SENZING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
      SENZING_SUBCOMMAND: rabbitmq
      SENZING_THREADS_PER_PROCESS: ${SENZING_THREADS_PER_PROCESS:-1}
    networks:
      - backend
    restart: always
    volumes:
      - ${SENZING_DIR:-/opt/senzing}:/opt/senzing

  api:
    image: senzing/senzing-api-server
    container_name: senzing-api-server
    command:
      - -httpPort 8080
      - -bindAddr all
      - -iniFile /opt/senzing/g2/python/G2Module.ini
    depends_on:
      - db2
    environment:
      SENZING_DATABASE_URL: "db2://${DB2_USERNAME:-db2inst1}:${DB2_PASSWORD:-db2inst1}@senzing-db2:50000/${DB2_DB:-G2}"
    networks:
      - backend
    ports:
      - 8889:8080
    restart: always
    volumes:
      - ${SENZING_DIR:-/opt/senzing}:/opt/senzing

networks:
  backend:
