version: '3'
services:

  sqliteweb:
    container_name: senzing-sqlite-web
    environment:
      SQLITE_DATABASE: G2C.db
    image: coleifer/sqlite-web:latest
    networks:
      - backend
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ${SENZING_DIR:-/opt/senzing}/g2/sqldb:/data

  initcontainer:
    container_name: senzing-init-container
    image: senzing/init-container:${SENZING_INIT_CONTAINER_VERSION:-1.1.0}
    networks:
      - backend
    restart: on-failure
    volumes:
      - ${SENZING_DIR:-/opt/senzing}:/opt/senzing

networks:
  backend:
